services:
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data:/data/db
    command: ["mongod", "--configsvr", "--replSet", "cfgrs", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_primary:
    image: mongo:latest
    container_name: shard1_primary
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.20
    volumes:
      - shard1-primary-data:/data/db
    command: ["mongod", "--shardsvr", "--replSet", "shard1rs", "--bind_ip_all", "--port", "27018"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_secondary1:
    image: mongo:latest
    container_name: shard1_secondary1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.21
    volumes:
      - shard1-secondary1-data:/data/db
    command: ["mongod", "--shardsvr", "--replSet", "shard1rs", "--bind_ip_all", "--port", "27018"]
    depends_on:
      - shard1_primary
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_secondary2:
    image: mongo:latest
    container_name: shard1_secondary2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.22
    volumes:
      - shard1-secondary2-data:/data/db
    command: ["mongod", "--shardsvr", "--replSet", "shard1rs", "--bind_ip_all", "--port", "27018"]
    depends_on:
      - shard1_primary
      - shard1_secondary1
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_primary:
    image: mongo:latest
    container_name: shard2_primary
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.30
    volumes:
      - shard2-primary-data:/data/db
    command: ["mongod", "--shardsvr", "--replSet", "shard2rs", "--bind_ip_all", "--port", "27019"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_secondary1:
    image: mongo:latest
    container_name: shard2_secondary1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.31
    volumes:
      - shard2-secondary1-data:/data/db
    command: ["mongod", "--shardsvr", "--replSet", "shard2rs", "--bind_ip_all", "--port", "27019"]
    depends_on:
      - shard2_primary
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_secondary2:
    image: mongo:latest
    container_name: shard2_secondary2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.32
    volumes:
      - shard2-secondary2-data:/data/db
    command: ["mongod", "--shardsvr", "--replSet", "shard2rs", "--bind_ip_all", "--port", "27019"]
    depends_on:
      - shard2_primary
      - shard2_secondary1
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    depends_on:
      - configSrv
      - shard1_primary
      - shard1_secondary1
      - shard1_secondary2
      - shard2_primary
      - shard2_secondary1
      - shard2_secondary2
    command: ["mongos", "--configdb", "cfgrs/configSrv:27017", "--bind_ip_all", "--port", "27020"]

  pymongo_api:
    container_name: pymongo_api
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongos_router
      - configSrv
      - shard1_primary
      - shard1_secondary1
      - shard1_secondary2
      - shard2_primary
      - shard2_secondary1
      - shard2_secondary2
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020/somedb"
      MONGODB_DATABASE_NAME: "somedb"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data:
  shard1-primary-data:
  shard1-secondary1-data:
  shard1-secondary2-data:
  shard2-primary-data:
  shard2-secondary1-data:
  shard2-secondary2-data: